### ISSUE TITLE
Building and Linking

### ISSUE THREAD

**Issue by Ryefalk** [jkriege2/TinyTIFF#6]
There are no clear instructions on how to link the library in the documentation. Can this be added? Otherwise just write a simple one liner on how the library is linked to a simple one file program in this issue.

**Comment by jkriege2** [comment]
Should be fixed by https://github.com/jkriege2/TinyTIFF/commit/8d9ae689b282852135dbe9695f0a0214d004ffec

**Comment by Ryefalk** [comment]
Just if someone finds this I used "-I/usr/local/include -L/usr/local/lib -lTinyTIFFShared_ -L/lib/x86_64-linux-gnu/libc.so.6 -L/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2" on ubuntu 18.04. So the name i got when installing was not TinyTIFF it was TinyTIFFShared_.

**Comment by jkriege2** [comment]
Hi!

how did you build you lib? I didn't expect TinyTIFFShared_ ... I would have either expected TinyTIFFShared or TinyTIFFShared_Debug/Release/... ... 

Another question: Why do you use the -L option to link against the libc and ld-linux? and not -l?

Best,
JAN

**Comment by jkriege2** [comment]
.... aaahhh ... I'm workin on Windows with QtCreator ... there the build-type is always set ... but it seems on Linux the build-type can be empty, which leads to the strange name addition. I fixed this for now by ensuring that if nothing else is set, the build-type is Release ...

**Comment by Ryefalk** [comment]
I followed the instructions in the documentation, but I don't think I set any build type. As to why -L over -l, for some reason ld (the linker) can't find them so i have to give the path. It should probably work in the normal case but I have abused this system a lot as I'm doing a lot of experimentation at the moment.
/usr/bin/ld: cannot find -llibc.so.6
/usr/bin/ld: cannot find -lld-linux-x86-64.so.2

**Comment by jkriege2** [comment]
As mentioned above ... the strange name with the trailing underscore was due to a not-set configuration. I changed the CMakeLists to fix that ... now _Release is the default, or you switch the decoration off completely using the appropriate CMake-option ().

I was wondering about using -L and -l ... as in my understanding -L is used to provide additional search paths for libs and -l to provide the lib name ... I think you can also provide the full lib-name to -l ... see https://gcc.gnu.org/onlinedocs/gcc-4.7.4/gcc/Link-Options.html#Link-Options ... but that's more out of interest ;-)

Were you able to check with my modifications? Is the explanation in http://jkriege2.github.io/TinyTIFF/page_useinstructions.html detailed enough?

Then I will close that issue ... if I should add anything more to the docu: Just let me know ;-)

**Comment by Ryefalk** [comment]
Thanks for the tip! That explanation seems enough for me. I will get back to you if I find some other weird stuff.
