### ISSUE TITLE
segfault crash reading planar rgb image

### ISSUE THREAD

**Issue by petke** [jkriege2/TinyTIFF#9]
I was hoping to use this library for reading the most common types of tiff files.
It seems that the library does not suppport color images, but only grayscale. As in 
interleaved/packed rgb is not supported, and it seems planar rgb causes a segfault crash.

I looked for a planar rgb to test and i found one in your test folder (galaxy_nocompression.tif). 
(I couldn't find any planar rgb tiff example files on the web, as those all seem to be interleaved. Maybe that's the most common format)

Steps to reproduce crash:
run "tinytiffreader_test" on the "galaxy_nocompression.tif" sample file. 
I simply renamed "galaxy_nocompression.tif" to "galaxy.tif" as thats the filename "tinytiffreader_test" expects. 

Output:
"
reading 'galaxy.tif' and checking read contents ... filesize = 2.664 MBytes
    ImageDescription:
ImageJ=1.51h
unit=inch
    frames: 1     [duration: 2.402 us  =  2.402000us ]
    size of frame 0: 965x965
Segmentation fault (core dumped)
"

I did a bit of investigation and i think the problem is that tinyTIFF seems to think the rgb888 image is rgb808 format, as in it fails to read the bits_per_sample of the 2nd channel (the green plane). The crash happens not when opening the file, but when reading sample data from 2nd channel.

Edit: 
On a related note. The code in the example programs only ever get the first channel. As in 0
TinyTIFFReader_getBitsPerSample(tiffr, 0)/8); 
TinyTIFFReader_getSampleData(tiffr, tmp, 0);
It would be nice if there was an example that read all channels of a color image.

**Comment by jkriege2** [comment]
Hi!

yes, the reader is very limited in its possibilities!
Keep in mind that this lib was originally designed as a pair to read 1-sample data generated by TinyTIFFWriter FAST.

Please also note that there have been some major updates yesterday. And galaxy_uncompressed.tif now generates very specific error message:
```
       TinyTIFF: ERROR reading frame 0, sample 0:in planar multi-sample data, stripcount has to be dividable by samplesperpixel
       TinyTIFF: ERROR reading frame 0, sample 1:in planar multi-sample data, stripcount has to be dividable by samplesperpixel
       TinyTIFF: ERROR reading frame 0, sample 2:in planar multi-sample data, stripcount has to be dividable by samplesperpixel
```

This is one of the limitations of how the reader works internally. I have plans to change that and improve support, but that may take some time. E.g. allow reading chunked data with internal reordering etz.

About the two problems in the reader_test:
- `TinyTIFFReader_getBitsPerSample(tiffr, 0)`: Yes, this is due to the fact that the library only allows reading images where all samples have the same bit-width (There should be a warning in the new version, when this is otherwise)
- `TinyTIFFReader_getSampleData(tiffr, tmp, 0);` that has been corrected in the new version from yesterday (unless I overlooked a spot ... then please let me know)

Best,
JAN

**Comment by jkriege2** [comment]
Also there is now a new reader code that gives better error messages. Eventually that code may be extended to cover chunked data and colormapped images!

**Comment by jkriege2** [comment]
https://github.com/jkriege2/TinyTIFF/commit/c9d5fd6eea798deba5151f6cebc9b3f63836995a introduces reader-code for chunky multi-sample data
